ClasspathResourceSchemaStringProvider to use full constructor instead of field injection
graphql-java-kickstart/graphql-spring-boot pull request #914
Opened 2023-01-11 08:57 UTC by sausageRoll

Hello,

I have tried to use native SB3 builds and faced NPE problem. It's related to graalvm nature of compile time boot.

The following changes helped me to solve it, please take a look
Thank you

2023-01-14 10:25 UTC, oliemansm commented
@eye-dee Thanks for your contribution!

2023-01-14 10:28 UTC, oliemansm requested changes
Can you change your commit message in line with conventional commits? See https://gist.github.com/Zekfad/f51cb06ac76e2457f11c80ed705c95a3

2023-01-15 08:39 UTC, eye-dee commented
Done
Please take a look

2023-01-15 18:41 UTC, oliemansm approved these changes

2023-01-16 09:40 UTC, merged